# Generated by Django 4.2.6 on 2024-10-01 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SNMPWalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=100)),
                ("snmp_port", models.IntegerField(default=161)),
                (
                    "snmp_version",
                    models.CharField(
                        choices=[("1", "SNMPv1"), ("2c", "SNMPv2c"), ("3", "SNMPv3")],
                        max_length=3,
                    ),
                ),
                (
                    "read_community_string",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "authentication_type",
                    models.CharField(
                        blank=True,
                        choices=[("None", "None"), ("MD5", "MD5"), ("SHA", "SHA")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "encryption_type",
                    models.CharField(
                        blank=True,
                        choices=[("None", "None"), ("AES", "AES"), ("DES", "DES")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "encryption_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "context_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "snmp_command",
                    models.CharField(
                        choices=[("snmpwalk", "SNMP Walk"), ("snmpget", "SNMP Get")],
                        max_length=10,
                    ),
                ),
                ("oid", models.CharField(max_length=100)),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("numeric", "Numeric OIDs"),
                            ("certification", "Certification Walk"),
                            ("hex", "Hex String"),
                        ],
                        max_length=15,
                    ),
                ),
                ("source_peer", models.CharField(max_length=100)),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GettingStartedA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appliance_action", models.CharField(max_length=50)),
                ("subnet_name", models.CharField(max_length=255)),
                ("start_ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("end_ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("email_server", models.CharField(max_length=255)),
                ("email_username", models.CharField(max_length=255)),
                ("email_password", models.CharField(max_length=255)),
                ("connection_security", models.CharField(max_length=50)),
                ("email_port", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
