# Generated by Django 4.2.6 on 2024-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GettingStartedA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appliance_action", models.CharField(max_length=50)),
                ("subnet_name", models.CharField(max_length=255)),
                ("start_ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("end_ip_address", models.GenericIPAddressField(protocol="IPv4")),
                ("email_server", models.CharField(max_length=255)),
                ("email_username", models.CharField(max_length=255)),
                ("email_password", models.CharField(max_length=255)),
                ("connection_security", models.CharField(max_length=50)),
                ("email_port", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
