# Generated by Django 4.2.6 on 2024-10-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SNMPWalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=100)),
                ("snmp_port", models.IntegerField(default=161)),
                (
                    "snmp_version",
                    models.CharField(
                        choices=[("1", "SNMPv1"), ("2c", "SNMPv2c"), ("3", "SNMPv3")],
                        max_length=3,
                    ),
                ),
                (
                    "read_community_string",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "authentication_type",
                    models.CharField(
                        blank=True,
                        choices=[("None", "None"), ("MD5", "MD5"), ("SHA", "SHA")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "encryption_type",
                    models.CharField(
                        blank=True,
                        choices=[("None", "None"), ("AES", "AES"), ("DES", "DES")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "encryption_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "context_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "snmp_command",
                    models.CharField(
                        choices=[("snmpwalk", "SNMP Walk"), ("snmpget", "SNMP Get")],
                        max_length=10,
                    ),
                ),
                ("oid", models.CharField(max_length=100)),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("numeric", "Numeric OIDs"),
                            ("certification", "Certification Walk"),
                            ("hex", "Hex String"),
                        ],
                        max_length=15,
                    ),
                ),
                ("source_peer", models.CharField(max_length=100)),
                ("result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
