# Generated by Django 4.2.6 on 2024-10-17 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DASHBOARD", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SNMPWalk",
        ),
    ]
