# Generated by Django 4.2.6 on 2025-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0003_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="session_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="session_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
