# Generated by Django 4.2.6 on 2025-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0004_useractivity_session_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="session_status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
