version: "3.9"

services:
  backend:
    build:
      context: ./ 
      dockerfile: Dockerfile
      args:
        HOST_IP: 50.17.3.155
    env_file:
      - .env.prod
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      args:
        ENV_FILE: .env.prod
    container_name: react
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./staticfiles:/app/staticfiles
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
