version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env.prod.be
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      args:
        ENV_FILE: .env.prod.fe
    image: nms-frontend
    container_name: frontend
    depends_on:
      - backend

  nginx:
    image: nms-frontend
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/staticfiles  # Django static files
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
